repos:
  # standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        name: check-added-large-files

      - id: check-case-conflict
        name: check-case-conflict

      - id: end-of-file-fixer
        name: end-of-file-fixer

  - repo: https://github.com/hakancelik96/unimport
    rev: 0.9.6
    hooks:
      - id: unimport
        name: formatter_unimport
        #TODO: Figure out why pyproject.toml doesn't get recognized by pre-commit
        args: [ --remove, --requirements, --include-star-import, --ignore-init, --gitignore ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: formatter_isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        name: typechecker_mypy

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: linter_flake8
        always_run: true
        language: python
